version: "3.9"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: cookbot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app/backend   # <-- matches WORKDIR
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: cookbot_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
